name: Minute Committer Test

on:
  schedule:
    # Runs every minute
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest
    
    # این بخش برای دادن دسترسی نوشتن اضافه شده است
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create a commit
        run: |
          # Create or update a file to ensure there is a change
          date > last_run.txt
          
          # Configure Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Add, commit, and push
          git add last_run.txt
          git commit -m "Test commit at $(date)"
          git push
